### PR TITLE
feat: support lint all input files even if some files lint failure

### PR DESCRIPTION
**Pull request by poppinlp**
Hi. This PR includes:

- feat: support lint all input files for [this issue](https://github.com/rasshofer/yaml-lint/issues/10)
- refactor: update test cases for linter
- test: add test cases for CLI
- chore: add code coverage badge in README
- chore: update dependencies

### CODE REVIEW

**Comment by poppinlp** [comment]
I've rebase your master into this branch to resolve the conflict. But seems some commits info doubled.
I'm sorry for that. :(

**Comment by niftylettuce** [comment]
Bump

**Comment by paulo-ferraz-oliveira** [comment]
It's possible this pull request is now outdated.

**Comment by rasshofer** [comment]
Better late than never: this has finally been fixed in v1.4.0 which was published a few minutes ago. Sorry for the delay! 🙈

**Pull request closed without merging**
