### PR TITLE
Update dependencies and some syntax

### PR DESCRIPTION
**Pull request by poppinlp**
Hi.
I use this package in my work recently. I find the open issues are also my problem. So i wanna do some fix. Before that i send this PR for little update:

- update dependencies
- use eslint instead of jshint( i'm not sure your attitude so just use recommended rules )
- use more es6 syntax since they are supported from node 4.x
- remove travis test for node 5.x and 7.x [since they are end of life](https://github.com/nodejs/Release)
- add travis test for node 9.x

There's no logic change. I'm not sure what i've done is good as your wish. So wish for your reply and i'm going to fix those issues.

### CODE REVIEW

**Comment by poppinlp** [comment]
@rasshofer 
Hi, are you there~ Should i go on or wait for your reply? :)

**Comment by rasshofer** [comment]
@poppinlp 
Thanks for your contribution. I’ll have a look at your changes (and all open issues) as soon as possible! :)

**Comment by rasshofer** [comment]
Thanks once again for your nice contribution. I released v1.1.0 including your changes some minutes ago.

**Comment by poppinlp** [comment]
Got it. Thanks. I'm going to deal with those issues. :)

**Pull request merged**
